FROM python:3.10

WORKDIR /app

COPY api_requirements.txt .
RUN pip install --no-cache-dir -r api_requirements.txt

# copy everything from our api directory to the working directory
COPY ./api .

CMD ["python", "./app.py"]
